PUT http://localhost:3001/api/notes/624331c9b0425c1cec950861
Content-Type: application/json

{
    "content": "This is a modification",
    "important": false
}

### Only send a content
PUT http://localhost:3001/api/notes/624331c9b0425c1cec950861
Content-Type: application/json

{
    "content": "This is a content modification"
}

### Only send an important
PUT http://localhost:3001/api/notes/624331c9b0425c1cec950861
Content-Type: application/json

{
    "important": true
}

### No there note
PUT http://localhost:3001/api/notes